spring:
  application:
    name: ProjetoFinalAccentureGrupo1


  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
